import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import { LegalPage } from "./pages/LegalPage";
import "./styles.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <LegalPage
      effectiveDate="August 18, 2026"
      intro="These Terms and Conditions govern your access to and use of the NoBogey mobile application, which connects golfers with tee-time bookings and caddie services at participating golf courses in the Philippines. By creating an account or using the App, you agree to these Terms. If you do not agree, please do not use the App."
      sections={[
        { title: "1. Eligibility", body: <><p>You must be at least 18 years old to create an account. Users below this age may use the App only under the supervision and account of a parent or legal guardian.</p><p>Caddies must meet their affiliated golf course’s or club’s verification requirements, including any required accreditation. By registering, you represent that all information you provide is accurate, current, and complete.</p></> },
        { title: "2. Account registration and verification", body: <><p>Golfers must create an account and provide accurate personal information to book tee times. Caddies must complete onboarding and verification before accepting bookings or walk-in assignments.</p><p>NoBogey may reject, suspend, or revoke caddie verification, including on information from an affiliated golf course. You are responsible for keeping your login credentials confidential and for activity under your account. We may suspend or terminate accounts that provide false information, violate these Terms, or are flagged for misconduct by a partner golf course.</p></> },
        { title: "3. Bookings, cancellations, and no-shows", body: <><p>Tee-time bookings are subject to the participating golf course’s availability and may be modified or cancelled under that course’s policies. Caddie assignments, including walk-in gap coverage, are facilitated through the matching system but are not guaranteed.</p><p>Bookings cancelled less than 12 hours before their scheduled start time may be subject to the cancellation fee shown in the App’s booking-confirmation screen. NoBogey is not responsible for delays, cancellations, or closures caused by the golf course, weather, or events outside our control.</p></> },
        { title: "4. Caddie-golfer matching", body: <><p>Matching is intended to pair golfers with caddies based on stated playstyle preferences and availability. It is a convenience feature only; NoBogey does not guarantee compatibility, caddie performance, or satisfaction with a match.</p><p>Golfers and caddies are independent participants. NoBogey is a technology platform and does not employ caddies. We are not responsible for a caddie’s or golfer’s conduct, performance, advice, or actions on or off the golf course.</p></> },
        { title: "5. Payments", body: <p>Certain bookings require fees through third-party payment gateway APIs, including GCash (operated by G-Xchange, Inc.) or other authorized financial services. By initiating payment, you agree to the applicable processor’s terms and privacy policies. Refunds, where applicable, are subject to NoBogey’s and/or the golf course’s cancellation policy.</p> },
        { title: "6. User conduct", body: <><p>You agree not to provide false or misleading registration or verification information; use the App unlawfully; harass, threaten, or discriminate against other users; circumvent booking, verification, or matching systems; or interfere with the App’s operation or security.</p><p>NoBogey may suspend or terminate accounts that violate this section.</p></> },
        { title: "7. Assumption of risk and limitation of liability", body: <><p>Golf is a physical activity with inherent risks, including injury, property damage, and exposure to outdoor conditions. By using the App to book tee times or caddie services, you acknowledge and accept these risks.</p><p>NoBogey does not own, operate, or manage golf courses and is not responsible for course conditions, the conduct of caddies or golfers, or incidents occurring during a round. To the maximum extent permitted by law, NoBogey is not liable for indirect, incidental, or consequential damages. Its aggregate liability for a claim will not exceed the net platform fees retained for the specific booking or the fees you paid to NoBogey in the preceding three months, whichever is lower.</p></> },
        { title: "8. Data privacy", body: <p>NoBogey collects and processes personal data, including caddie identity-verification details, under the Philippine Data Privacy Act of 2012 (Republic Act No. 10173) and our Privacy Policy. By using the App, you consent to the collection, use, and processing described there.</p> },
        { title: "9. Intellectual property", body: <p>All NoBogey content, trademarks, logos, and software are the property of NoBogey or its licensors. You may not copy, modify, distribute, or reverse-engineer any part of the App without prior written consent.</p> },
        { title: "10. Suspension and termination", body: <p>NoBogey may suspend or terminate access, with or without notice, for conduct that violates these Terms, harms other users, or is fraudulent. You may stop using the App and request account deletion at any time through support or the in-app option.</p> },
        { title: "11. Changes to these Terms", body: <p>We may update these Terms from time to time. We will communicate material changes through the App, and continued use after those changes constitutes acceptance. Each version will be dated and numbered for reference.</p> },
        { title: "12. Governing law and dispute resolution", body: <p>These Terms are governed by the laws of the Republic of the Philippines. Disputes must first be addressed through good-faith negotiation and, if unresolved, submitted to the appropriate courts of Metro Manila, Philippines.</p> },
        { title: "13. Contact us", body: <p>For questions about these Terms, email <a className="font-medium text-forest underline underline-offset-4" href="mailto:nobogeyofficial@gmail.com">nobogeyofficial@gmail.com</a>.</p> }
      ]}
      title="Terms & Conditions"
      version="1.0"
    />
  </StrictMode>
);
