import { router } from "expo-router";
import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, spacing } from "@nobogey/ui";
import { Button } from "../../ui/primitives";
import NoBogeyLogo from "../../../../../assets/logo/NoBogey-Logo.png";

type Mode = "login" | "register";
type Role = "golfer" | "caddie";

export function SplashScreen() {
  return <SafeAreaView edges={["top", "bottom"]} style={styles.splash}><View style={styles.splashContent}><Image accessibilityLabel="NoBogey logo" resizeMode="contain" source={NoBogeyLogo} style={styles.logo} /><View style={styles.splashCopy}><Text accessibilityRole="header" style={styles.splashTitle}>Your best round starts with the right caddie.</Text><Text style={styles.splashText}>Find a trusted local caddie, request a tee time, and keep every booking in one place.</Text></View><Button accessibilityLabel="Get started" onPress={() => router.replace("/auth")}>Get started</Button><Pressable accessibilityLabel="Preview the app" accessibilityRole="button" onPress={() => router.replace("/home")}><Text style={styles.secondaryLink}>Preview with placeholder data</Text></Pressable></View></SafeAreaView>;
}

export function AuthScreen() {
  const [mode, setMode] = useState<Mode>("login");
  const [role, setRole] = useState<Role>("golfer");
  const destination = role === "caddie" ? "/caddie-dashboard" : "/home";
  const submitLabel = mode === "login" ? "Log in" : `Create ${role} account`;

  return <SafeAreaView edges={["top", "bottom"]} style={styles.authSafe}><ScrollView contentContainerStyle={styles.authContent} keyboardShouldPersistTaps="handled"><View style={styles.authHeader}><Image accessibilityLabel="NoBogey logo" resizeMode="contain" source={NoBogeyLogo} style={styles.authLogo} /><Text accessibilityRole="header" style={styles.authTitle}>{mode === "login" ? "Welcome back." : "Join the fairway."}</Text><Text style={styles.authSubtitle}>{mode === "login" ? "Log in to manage your next round." : "Choose how you’ll use NoBogey. You can update this later."}</Text></View><View style={styles.modeTabs}><Tab active={mode === "login"} label="Log in" onPress={() => setMode("login")} /><Tab active={mode === "register"} label="Register" onPress={() => setMode("register")} /></View>{mode === "register" && <View style={styles.roleGroup}><Text style={styles.fieldLabel}>I am joining as a</Text><View style={styles.roleTabs}><RoleTab active={role === "golfer"} description="Book a caddie for your round" icon="⛳" label="Golfer" onPress={() => setRole("golfer")} /><RoleTab active={role === "caddie"} description="Manage your availability" icon="🏌️" label="Caddie" onPress={() => setRole("caddie")} /></View></View>}<View style={styles.form}>{mode === "register" && <Field label="Full name" placeholder="e.g. Mia Santos" />}{mode === "register" && role === "caddie" && <Field label="Home course" placeholder="Choose your home course" />}<Field keyboardType="email-address" label="Email address" placeholder="you@example.com" /><Field label="Password" placeholder="••••••••" secureTextEntry /><Button accessibilityLabel={submitLabel} onPress={() => router.replace(destination)}>{submitLabel}</Button></View><Text style={styles.placeholderNote}>Placeholder only — authentication and account approval will connect to the backend later.</Text><Pressable accessibilityLabel="Return to welcome screen" accessibilityRole="button" onPress={() => router.replace("/")}><Text style={styles.secondaryLink}>Back to welcome</Text></Pressable></ScrollView></SafeAreaView>;
}

function Field({ label, ...inputProps }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor="#788179" style={styles.input} {...inputProps} /></View>; }
function Tab({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected: active }} onPress={onPress} style={[styles.modeTab, active && styles.modeTabActive]}><Text style={[styles.modeTabText, active && styles.modeTabTextActive]}>{label}</Text></Pressable>; }
function RoleTab({ active, description, icon, label, onPress }: { active: boolean; description: string; icon: string; label: string; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={onPress} style={[styles.roleTab, active && styles.roleTabActive]}><Text style={styles.roleIcon}>{icon}</Text><View style={styles.roleCopy}><Text style={styles.roleTitle}>{label}</Text><Text style={styles.roleDescription}>{description}</Text></View><View style={[styles.radio, active && styles.radioActive]}>{active && <View style={styles.radioDot} />}</View></Pressable>; }

const styles = StyleSheet.create({
  authContent: { gap: spacing.xl, padding: spacing.xl, paddingTop: 48 }, authHeader: { gap: spacing.sm }, authLogo: { height: 42, width: 42 }, authSafe: { backgroundColor: "#FAF9F6", flex: 1 }, authSubtitle: { color: "#617067", fontSize: 16, lineHeight: 23 }, authTitle: { color: "#143B2A", fontSize: 34, fontWeight: "900", letterSpacing: -1 }, field: { gap: 7 }, fieldLabel: { color: "#416052", fontSize: 13, fontWeight: "800" }, form: { gap: spacing.lg }, input: { backgroundColor: "#FFFFFF", borderColor: "#CBD4CC", borderCurve: "continuous", borderRadius: 12, borderWidth: 1, color: "#16231C", fontSize: 16, minHeight: 52, paddingHorizontal: 14 }, modeTab: { alignItems: "center", borderRadius: 10, flex: 1, justifyContent: "center", minHeight: 44 }, modeTabActive: { backgroundColor: "#FFFFFF" }, modeTabText: { color: "#68756C", fontSize: 15, fontWeight: "700" }, modeTabTextActive: { color: "#174B32" }, modeTabs: { backgroundColor: "#E4EAE4", borderRadius: 12, flexDirection: "row", padding: 4 }, placeholderNote: { color: "#6A706B", fontSize: 12, lineHeight: 17, textAlign: "center" }, radio: { alignItems: "center", borderColor: "#8AA092", borderRadius: 12, borderWidth: 1, height: 24, justifyContent: "center", width: 24 }, radioActive: { borderColor: colors.primary }, radioDot: { backgroundColor: colors.primary, borderRadius: 6, height: 12, width: 12 }, roleCopy: { flex: 1, gap: 2 }, roleDescription: { color: "#647067", fontSize: 12 }, roleGroup: { gap: spacing.sm }, roleIcon: { fontSize: 22 }, roleTab: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#CBD4CC", borderCurve: "continuous", borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 12, padding: 14 }, roleTabActive: { borderColor: colors.primary, borderWidth: 2, padding: 13 }, roleTabs: { gap: spacing.sm }, roleTitle: { color: "#173D2C", fontSize: 16, fontWeight: "800" }, secondaryLink: { color: "#1C5E3E", fontSize: 15, fontWeight: "800", textAlign: "center" }, splash: { backgroundColor: "#174B32", flex: 1 }, splashContent: { flex: 1, gap: 30, justifyContent: "flex-end", padding: 28, paddingBottom: 42 }, splashCopy: { gap: 12 }, splashText: { color: "#DCE9DD", fontSize: 16, lineHeight: 23 }, splashTitle: { color: "#FFFFFF", fontSize: 39, fontWeight: "900", letterSpacing: -1.4, lineHeight: 44 }, logo: { alignSelf: "center", height: 168, marginBottom: "auto", marginTop: 80, width: 168 }
});
