import { MaterialCommunityIcons } from "@expo/vector-icons";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, spacing } from "@nobogey/ui";
import { Card } from "../../ui/primitives";
import { backToPreviousPage } from "../../ui/navigation";
import { ResponsiveContent } from "../../ui/ResponsiveContent";
import { useAppSession } from "../session/AppSession";
import { selectedCaddieAvatar } from "./avatar-options";
import { experienceLabels, golferSkillLabels, selectedCourse, skillOptions } from "./model";
import { VerificationStatusScreen } from "./VerificationStatusScreen";

export function CaddiePublicProfileScreen() {
  const { caddieOnboarding: draft } = useAppSession();
  const course = selectedCourse(draft);
  if (draft.verificationStatus !== "verified") return <VerificationStatusScreen />;
  const skills = draft.skills.map((id) => skillOptions.find((skill) => skill[0] === id)?.[1] ?? id);
  return <SafeAreaView edges={["top", "bottom"]} style={styles.safe}><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.scroll}><ResponsiveContent style={styles.content}><View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" onPress={() => backToPreviousPage("/caddie/dashboard")}><Text style={styles.back}>‹ Back</Text></Pressable><Text accessibilityRole="header" style={styles.title}>My Profile</Text><View style={styles.verified}><Text style={styles.verifiedText}>✓ Verified</Text></View></View><Card style={styles.card}>{draft.profilePhotoUri ? <ProfileAvatar avatar={draft.profilePhotoUri} name={draft.fullName} /> : null}<Text style={styles.name}>{draft.fullName}</Text><Text style={styles.course}>{course?.name}</Text><Text style={styles.meta}>{draft.yearsExperience ? experienceLabels[draft.yearsExperience] : ""} experience</Text><Text style={styles.tagline}>{draft.tagline}</Text>{draft.bio ? <Text style={styles.body}>{draft.bio}</Text> : null}<ProfileSection label="Skills" values={skills} /><ProfileSection label="Preferred golfers" values={draft.preferredGolferSkillRange.map((range) => golferSkillLabels[range])} /><ProfileSection label="Languages" values={draft.languages} /><View style={styles.section}><Text style={styles.sectionTitle}>Credentials</Text>{draft.credentials.length ? draft.credentials.map((credential) => <Text key={credential.id} style={styles.body}>{credential.name} · {credential.issuer} <Text style={styles.credentialState}>Verified</Text></Text>) : <Text style={styles.body}>No credentials listed.</Text>}</View><View style={styles.section}><Text style={styles.sectionTitle}>Highlights</Text>{draft.highlights.map((highlight) => <Text key={highlight.id} style={styles.body}>• {highlight.title}{highlight.year ? ` (${highlight.year})` : ""}</Text>)}</View></Card></ResponsiveContent></ScrollView></SafeAreaView>;
}
function ProfileAvatar({ avatar, name }: { avatar: string; name: string }) { const option = selectedCaddieAvatar(avatar); return <View accessibilityLabel={`${name} ${option.label} avatar icon`} accessibilityRole="image" style={styles.photo}><MaterialCommunityIcons color={colors.surface} name={option.icon} size={56} /></View>; }
function ProfileSection({ label, values }: { label: string; values: string[] }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{label}</Text>{values.length ? <View style={styles.chips}>{values.map((value) => <Text key={value} style={styles.chip}>{value}</Text>)}</View> : <Text style={styles.body}>Not added.</Text>}</View>; }
const styles = StyleSheet.create({ back: { color: colors.primary, fontSize: 14, fontWeight: "800" }, body: { color: colors.textMuted, fontSize: 14, lineHeight: 21 }, card: { gap: spacing.md }, chip: { backgroundColor: "#E4EEE6", borderRadius: 999, color: colors.fairwayDark, fontSize: 12, fontWeight: "700", overflow: "hidden", paddingHorizontal: 10, paddingVertical: 6 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, content: { gap: spacing.xl, padding: spacing.lg, paddingBottom: 36 }, course: { color: colors.fairwayDark, fontSize: 15, fontWeight: "800" }, credentialState: { color: colors.primary, fontWeight: "900" }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", minHeight: 44 }, meta: { color: colors.textMuted, fontSize: 13 }, name: { color: colors.text, fontSize: 28, fontWeight: "900", letterSpacing: -0.7 }, photo: { alignItems: "center", backgroundColor: colors.fairway, borderRadius: 48, height: 96, justifyContent: "center", width: 96 }, safe: { backgroundColor: colors.canvas, flex: 1 }, scroll: { flexGrow: 1 }, section: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, gap: 8, paddingTop: spacing.md }, sectionTitle: { color: colors.fairwayDark, fontSize: 13, fontWeight: "900", letterSpacing: 0.7, textTransform: "uppercase" }, tagline: { color: colors.fairwayDark, fontSize: 18, fontWeight: "800", lineHeight: 24 }, title: { color: colors.text, fontSize: 20, fontWeight: "900" }, verified: { backgroundColor: "#E4EEE6", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5 }, verifiedText: { color: colors.primary, fontSize: 11, fontWeight: "900" } });
