import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, spacing } from "@nobogey/ui";
import { Button, Card } from "../../ui/primitives";
import { ResponsiveContent } from "../../ui/ResponsiveContent";
import { useAppSession } from "../session/AppSession";
import { selectedCourse } from "./model";

export function VerificationStatusScreen() {
  const { caddieOnboarding: draft } = useAppSession();
  const course = selectedCourse(draft);
  const status = draft.verificationStatus;
  const submittedAt = draft.verificationRequest?.submittedAt ?? draft.submittedAt;
  const name = course?.name ?? "your home club";
  const update = () => router.replace({ pathname: "/caddie/onboarding", params: { step: status === "changes_requested" ? "2" : "5" } });
  const isVerified = status === "verified";
  const isChanges = status === "changes_requested";
  const isRejected = status === "rejected";
  return <SafeAreaView edges={["top", "bottom"]} style={styles.safe}><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.scroll}><ResponsiveContent style={styles.content}><Text accessibilityRole="header" style={styles.title}>{isVerified ? "You're verified" : isChanges ? "Your club needs more information" : isRejected ? "We couldn't verify your caddie profile" : "Your profile is being verified"}</Text><Text style={styles.subtitle}>{isVerified ? `Your caddie profile has been verified by ${name}.` : isChanges || isRejected ? draft.changeReason ?? "Your club has asked you to review the information submitted with your profile." : "We've sent your information to your home club for verification. You'll be able to use your verified caddie profile once the club completes its review."}</Text><Card style={styles.clubCard}><Text style={styles.kicker}>{isVerified ? "VERIFIED BY" : "VERIFICATION BY"}</Text><Text style={styles.club}>{name}</Text>{course ? <Text style={styles.location}>{course.city}, {course.region}</Text> : null}</Card>{!isVerified && !isChanges && !isRejected ? <Timeline submittedAt={submittedAt} /> : null}{isVerified ? <View style={styles.actions}><Button accessibilityLabel="View my verified profile" onPress={() => router.replace("/caddie/profile")}>View My Profile</Button><Button accessibilityLabel="Go to caddie dashboard" onPress={() => router.replace("/caddie/dashboard")} variant="secondary">Go to Dashboard</Button></View> : isChanges ? <Button accessibilityLabel="Update requested information" onPress={update}>Update Information</Button> : isRejected ? <View style={styles.actions}><Button accessibilityLabel="Review submitted information" onPress={() => router.replace({ pathname: "/caddie/onboarding", params: { step: "5", readOnly: "true" } })}>Review Information</Button><Button accessibilityLabel="Contact support" onPress={() => {}} variant="secondary">Contact Support</Button></View> : <View style={styles.actions}><Button accessibilityLabel="View submitted profile" onPress={() => router.replace({ pathname: "/caddie/onboarding", params: { step: "5", readOnly: "true" } })} variant="secondary">View submitted profile</Button><Text style={styles.noAction}>No action is required right now. We’ll update your account when your club completes the review.</Text></View>}</ResponsiveContent></ScrollView></SafeAreaView>;
}
function Timeline({ submittedAt }: { submittedAt?: string | undefined }) { return <Card style={styles.timeline}><TimelineRow detail={submittedAt ? new Date(submittedAt).toLocaleString() : "Complete"} status="Complete" title="Profile submitted" /><TimelineRow detail="Your club is reviewing your caddie registry and submitted credentials." status="In progress" title="Club review" /><TimelineRow detail="Waiting for club review to complete." status="Waiting" title="Verification complete" /></Card>; }
function TimelineRow({ detail, status, title }: { detail: string; status: string; title: string }) { return <View style={styles.timelineRow}><View style={styles.timelineDot} /><View style={styles.timelineCopy}><Text style={styles.timelineTitle}>{title}</Text><Text style={styles.timelineDetail}>{detail}</Text></View><Text style={styles.status}>{status}</Text></View>; }
const styles = StyleSheet.create({ actions: { gap: spacing.md }, club: { color: colors.text, fontSize: 20, fontWeight: "900" }, clubCard: { gap: 5 }, content: { gap: spacing.xl, padding: spacing.lg, paddingBottom: 36 }, kicker: { color: colors.primary, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, location: { color: colors.textMuted, fontSize: 14 }, noAction: { color: colors.textMuted, fontSize: 14, lineHeight: 21, textAlign: "center" }, safe: { backgroundColor: colors.canvas, flex: 1 }, scroll: { flexGrow: 1 }, status: { color: colors.primary, fontSize: 12, fontWeight: "900" }, subtitle: { color: colors.textMuted, fontSize: 16, lineHeight: 23 }, timeline: { gap: spacing.lg }, timelineCopy: { flex: 1, gap: 3 }, timelineDetail: { color: colors.textMuted, fontSize: 13, lineHeight: 18 }, timelineDot: { backgroundColor: colors.primary, borderRadius: 6, height: 12, marginTop: 4, width: 12 }, timelineRow: { flexDirection: "row", gap: 10 }, timelineTitle: { color: colors.fairwayDark, fontSize: 15, fontWeight: "900" }, title: { color: colors.text, fontSize: 32, fontWeight: "900", letterSpacing: -1 } });
